### ISSUE TITLE
Nombre Comercial

### ISSUE THREAD

**Issue by juhenriquez** [indexa-git/l10n_do_currency_update#17]
#### Impacted versions
11.0, 12.0, 13.0

**Describe the solution you'd like**
Al momento de crear un cliente traer nombre comercial, se pueda utilizar para busquedas y sea visible en vistas.

**Comment by jose-pcg** [comment]
- En el branch 11.0 no existe el módulo **l10n_do_rnc_validation**
- El nombre comercial "tradename" se escribirá en el campo `ref`
- No se hará nada a nivel de vistas con este campo ya que no es el objetivo de este módulo
- Este issue será cerrado en el PR #60
