### ISSUE TITLE
l10n_do_currency_update BCD currency not available till 4pm

### ISSUE THREAD

**Issue by juhenriquez** [indexa-git/l10n_do_currency_update#18]
#### Impacted versions
ALL
#### Steps to reproduce
send request to end point using Dominican Republic Central Bank /api/rates?bank=bcd&date=2020-05-15
#### Current behavior
Will not get a currency rate till 4pm
#### Expected behavior
Get currency rate around 9-10AM

**Comment by jose-pcg** [comment]
@juhenriquez esto no es un issue del módulo.
