### ISSUE TITLE
[BUG] l10n_do_rnc_validation: Expected singleton error when creating new contact 

### ISSUE THREAD

**Issue by jose-pcg** [indexa-git/l10n_do_currency_update#45]
#### Impacted versions

12.0, 13.0

#### Steps to reproduce

Crear un contacto nuevo

#### Current behavior

Al parecer, si no se obtiene data sobre el RNC por medio del API, da el error

#### Expected behavior

Que no de error 🤷🏻‍♂️

**Comment by juhenriquez** [comment]
![image](https://user-images.githubusercontent.com/8250019/90014354-f00e2f80-dc74-11ea-8a2a-4937fe69c35d.png)

Unkown issue reproduction, seems when empty response from API
