### ISSUE TITLE
Validacion RNC

### ISSUE THREAD

**Issue by angelgrullon10** [indexa-git/l10n_do_currency_update#67]
#### Impacted versions
V12
#### Current behavior
Problemas con la validación de RNC al registrar clientes y proveedores, error en la consulta.

**Comment by jose-pcg** [comment]
@angelgrullon10 
No estás aportando suficiente información para reproducir el problema. Por favor utiliza [esta](https://github.com/indexa-git/l10n-dominicana/wiki/Contributing#reporting-issues) guia para redactar mejor el issue.
